/*
 * Copyright (c) 2024 ZMK Contributors
 * SPDX-License-Identifier: MIT
 *
 * Shared types and extern declarations for the claude_view animation system.
 *
 * claude_art.c is generated by tools/nicview_frames.py. This header is the
 * stable ABI between the generated data file and custom_status_screen.c.
 */

#pragma once

#include <lvgl.h>
#include <zephyr/types.h>

/* One named animation: a pointer array of LVGL image descriptors + metadata. */
struct claude_animation {
    const char              *name;
    const lv_img_dsc_t * const *frames;
    uint8_t                  count;
    uint16_t                 ms_per_frame;
};

/* Provided by assets/claude_art.c (generated). */
extern const struct claude_animation animations[];
extern const uint8_t                 animation_count;

/* Legacy single-animation aliases (first entry in animations[]). */
extern const lv_img_dsc_t * const * const claude_frames;
extern const uint8_t  claude_frame_count;
extern const uint16_t claude_frame_ms;
