/*
 * Copyright (c) 2024 ZMK Contributors
 * SPDX-License-Identifier: MIT
 *
 * Claude View — custom peripheral status screen for ZMK nice!view.
 *
 * Animation data and the animations[] table are defined in assets/claude_art.c
 * (generated by tools/nicview_frames.py --manifest tools/animations.toml).
 *
 * Switching animations at runtime:
 *   Press a key bound to &anim_select N  to jump to animation index N.
 *   Press a key bound to &anim_next      to cycle forward through all animations.
 *
 * This file never needs to change when you add or regenerate animations.
 */

#include <zephyr/kernel.h>
#include <lvgl.h>

#include "assets/claude_art.h"

/* Declared in behaviors/anim_select.c */
extern uint8_t zmk_claude_view_get_animation(void);

/* ── Module state ──────────────────────────────────────────────────────── */

static lv_obj_t   *anim_widget  = NULL;
static uint8_t     active_anim  = UINT8_MAX;  /* forces initial load */

/* ── Helpers ───────────────────────────────────────────────────────────── */

static void apply_animation(uint8_t idx) {
    if (idx >= animation_count) {
        idx = 0;
    }
    const struct claude_animation *a = &animations[idx];
    lv_animimg_set_src(anim_widget, (const void **)a->frames, a->count);
    lv_animimg_set_duration(anim_widget, (uint32_t)a->ms_per_frame * a->count);
    lv_animimg_set_repeat_count(anim_widget, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(anim_widget);
    active_anim = idx;
}

/* ── lv_timer callback (runs on the LVGL display work queue) ────────────── */

static void anim_switch_cb(lv_timer_t *timer) {
    uint8_t requested = zmk_claude_view_get_animation();
    if (requested != active_anim) {
        apply_animation(requested);
    }
}

/* ── Screen init (called once by ZMK display subsystem) ────────────────── */

lv_obj_t *zmk_display_status_screen(void) {
    lv_obj_t *screen = lv_obj_create(NULL);

    anim_widget = lv_animimg_create(screen);
    lv_obj_align(anim_widget, LV_ALIGN_CENTER, 0, 0);

    /* Load the first animation immediately */
    apply_animation(0);

    /* Poll for animation-index changes every 50 ms.
     * The timer runs on the LVGL work queue, so lv_animimg_set_src() is safe. */
    lv_timer_create(anim_switch_cb, 50, NULL);

    return screen;
}
