/*
 * Copyright (c) 2024 ZMK Contributors
 * SPDX-License-Identifier: MIT
 *
 * Claude View — custom peripheral status screen for ZMK nice!view.
 *
 * Animation data lives in assets/claude_art.c (generated by
 * tools/nicview_frames.py --manifest tools/animations.toml).
 *
 * Switching animations from keys on the LEFT (central) half
 * ---------------------------------------------------------
 * Use &anim_pick N or &anim_cycle in your keymap. Those behaviors use
 * BEHAVIOR_LOCALITY_GLOBAL; ZMK relays them to the BLE peripheral over the
 * stock split "run behavior" transport (same mechanism as RGB underglow).
 *
 * Boot default: INITIAL_ANIM in behaviors/anim_select.c (0 = wave, 1 = gym).
 */

#include <zephyr/kernel.h>
#include <lvgl.h>

#include "assets/claude_art.h"

extern uint8_t zmk_claude_view_get_animation(void);

static lv_obj_t *anim_widget = NULL;
static uint8_t   active_anim = UINT8_MAX;

static void apply_animation(uint8_t idx) {
    if (idx >= animation_count) {
        idx = 0;
    }
    if (idx == active_anim) {
        return;
    }
    const struct claude_animation *a = &animations[idx];
    lv_animimg_set_src(anim_widget, (const void **)a->frames, a->count);
    lv_animimg_set_duration(anim_widget, (uint32_t)a->ms_per_frame * a->count);
    lv_animimg_set_repeat_count(anim_widget, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(anim_widget);
    active_anim = idx;
}

static void anim_refresh_cb(lv_timer_t *timer) {
    ARG_UNUSED(timer);
    uint8_t requested = zmk_claude_view_get_animation();
    if (requested != active_anim) {
        apply_animation(requested);
    }
}

lv_obj_t *zmk_display_status_screen(void) {
    lv_obj_t *screen = lv_obj_create(NULL);

    anim_widget = lv_animimg_create(screen);
    lv_obj_align(anim_widget, LV_ALIGN_CENTER, 0, 0);

    apply_animation(zmk_claude_view_get_animation());

    lv_timer_create(anim_refresh_cb, 50, NULL);

    return screen;
}
