/*
 * Copyright (c) 2024 ZMK Contributors
 * SPDX-License-Identifier: MIT
 *
 * Claude View — custom peripheral status screen for ZMK nice!view.
 *
 * Animation data and the animations[] table are defined in assets/claude_art.c
 * (generated by tools/nicview_frames.py --manifest tools/animations.toml).
 *
 * Animation switching via keybinding
 * ------------------------------------
 * Toggling layer ANIM_LAYER (default: 4) switches to the next animation.
 * Layer 4 active → animation index 1 (gym).
 * Layer 4 inactive → animation index 0 (wave).
 *
 * Add to your keymap Fn layer:  &tog 4   (or &mo 4 for momentary hold)
 * Layer 4 itself is all &trans so it does not affect any keybindings.
 *
 * This works cross-split because ZMK forwards layer state from the central
 * to the peripheral via BLE notifications — no ZMK core changes needed.
 */

#include <zephyr/kernel.h>
#include <lvgl.h>

#include <zmk/event_manager.h>
#include <zmk/events/layer_state_changed.h>

#include "assets/claude_art.h"

/* Layer whose activation switches to the alternate animation.
 * Must match the layer index in eyelash_corne.keymap. */
#define ANIM_LAYER 4

/* Provided by behaviors/anim_select.c */
extern uint8_t zmk_claude_view_get_animation(void);
extern void    zmk_claude_view_set_animation(uint8_t idx);

/* ── Module state ──────────────────────────────────────────────────────── */

static lv_obj_t *anim_widget = NULL;
static uint8_t   active_anim = UINT8_MAX; /* force initial load */

/* ── Helpers ───────────────────────────────────────────────────────────── */

static void apply_animation(uint8_t idx) {
    if (idx >= animation_count) {
        idx = 0;
    }
    if (idx == active_anim) {
        return;
    }
    const struct claude_animation *a = &animations[idx];
    lv_animimg_set_src(anim_widget, (const void **)a->frames, a->count);
    lv_animimg_set_duration(anim_widget, (uint32_t)a->ms_per_frame * a->count);
    lv_animimg_set_repeat_count(anim_widget, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(anim_widget);
    active_anim = idx;
    zmk_claude_view_set_animation(idx);
}

/* ── Layer state listener (runs on LVGL work queue via ZMK event system) ── */

static int layer_changed_handler(const zmk_event_t *eh) {
    const struct zmk_layer_state_changed *ev = as_zmk_layer_state_changed(eh);
    if (ev == NULL || ev->layer != ANIM_LAYER) {
        return ZMK_EV_EVENT_BUBBLE;
    }
    /* Layer 4 activated → gym (index 1); deactivated → wave (index 0) */
    apply_animation(ev->state ? 1 : 0);
    return ZMK_EV_EVENT_BUBBLE;
}

ZMK_LISTENER(claude_view_anim_listener, layer_changed_handler);
ZMK_SUBSCRIPTION(claude_view_anim_listener, zmk_layer_state_changed);

/* ── Screen init (called once by ZMK display subsystem) ────────────────── */

lv_obj_t *zmk_display_status_screen(void) {
    lv_obj_t *screen = lv_obj_create(NULL);

    anim_widget = lv_animimg_create(screen);
    lv_obj_align(anim_widget, LV_ALIGN_CENTER, 0, 0);

    apply_animation(zmk_claude_view_get_animation());

    return screen;
}
